name: Build and Deploy

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Build & Push Docker Image to Docker Hub, then deploy to production server'
        required: true
        default: 'Manual build from GitHub UI'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  app-name: "cd-docker-nestjs-react-postgres"

jobs:
  build:
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
  deploy:
    needs: build
    runs-on: [ self-hosted ]
    defaults:
      run:
        working-directory: '/home/quochao/docker-nestjs-react-postgres'
    steps:
      - name: Build and run
        run: docker compose up -d --build
